quarkus:
  http:
    host: 0.0.0.0
    test-port: 8083
    test-ssl-port: 8446

  container-image:
    group: ubitech

  datasource:
    db-kind: postgresql
    jdbc:
      driver: org.postgresql.Driver

  hibernate-orm:
    jdbc:
      timezone: "UTC"
    database:
      generation: validate
    sql-load-script: no-file

  ssl:
    native: false

  # oidc:
  #   auth-server-url:
  #   client-id:
  #   credentials:
  #     secret:

  log:
    console:
      enable: true
      color: true
      format: "%d{HH:mm:ss} %-5p traceId=%X{traceId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n"

  liquibase:
    migrate-at-start: true

  banner:
    path: portal-banner.txt

  jackson:
    accept-case-insensitive-enums: true
    timezone: "UTC"

  swagger-ui:
    title: Palantir Portal API

  minio:
    url:
    access-key:
    secret-key:

# keycloak:
#   baseurl:
#   realm:
#   admin:
#     username:
#     password:

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      jdbc:
        url: org.postgresql.Driver
      metrics:
        enabled: true
    hibernate-orm:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      log:
        sql: true
    mailer:
      mock: true
  # domain:

"%test":
  quarkus:
    datasource:
      db-kind: h2
      jdbc:
        url: jdbc:h2:mem:db
    hibernate-orm:
      dialect: org.hibernate.dialect.H2Dialect
      log:
        sql: true
    mailer:
      mock: true

"%prod":
  quarkus:
    package:
      type: uber-jar
    datasource:
      db-kind: postgresql
      jdbc:
        url: org.postgresql.Driver
      metrics:
        enabled: true
    hibernate-orm:
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      log:
        sql: false
    mailer:
      mock: false
    liquibase:
      contexts: "!fake-data"
  # domain:
